[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-L", "/opt/homebrew/Cellar/mingw-w64/12.0.0_3/toolchain-x86_64/lib/gcc/x86_64-w64-mingw32/15.1.0",
    "-L", "/opt/homebrew/Cellar/mingw-w64/12.0.0_3/toolchain-x86_64/x86_64-w64-mingw32/lib"
]
